# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

em_hmm <- function(pa_in, pb_in, pi0a_in, pi0b_in) {
    .Call('_CoHiM_em_hmm', PACKAGE = 'CoHiM', pa_in, pb_in, pi0a_in, pi0b_in)
}

replis <- function(pi, A, f1, f2) {
    .Call('_CoHiM_replis', PACKAGE = 'CoHiM', pi, A, f1, f2)
}

fdr <- function(repLIS) {
    .Call('_CoHiM_fdr', PACKAGE = 'CoHiM', repLIS)
}

